name: Autobuild

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  Autobuild:
    runs-on: ubuntu-latest
    steps:
      - name: Set autocrlf
        run: git config --global core.autocrlf true

      - uses: actions/checkout@v3

      - name: "Get c4group executable"
        run: |
          curl -L https://github.com/legacyclonk/LegacyClonk/releases/download/v353/LegacyClonk-Linux-x64.tar.gz | tar xz c4group
          echo "C4GROUP=$PWD/c4group" >> $GITHUB_ENV

      - name: Build
        run: |
          make -j$(nproc) C4GROUP=$C4GROUP
          rm packed/.exists
          cd packed
          ../updates/make_group_updates.sh
      - uses: actions/upload-artifact@v3
        with:
          name: sc-content
          path: packed/sc_content.zip
      - name: "Release"
        uses: softprops/action-gh-release@v1
        with:
          files: packed/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
