name: Autobuild

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  Autobuild:
    runs-on: ubuntu-latest
    env:
      IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Set autocrlf
        run: git config --global core.autocrlf true

      - uses: actions/checkout@v3

      - name: "Get c4group executable"
        run: |
          curl -L https://github.com/legacyclonk/LegacyClonk/releases/download/v353/LegacyClonk-Linux-x64.tar.gz | tar xz c4group
          echo "C4GROUP=$PWD/c4group" >> $GITHUB_ENV

      - name: Build
        run: |
          make -j$(nproc) C4GROUP=$C4GROUP
          rm packed/.exists
          cd packed
# We don't need c4u update files right now, we do a fresh release
#          ../updates/make_group_updates.sh
      - name: Prepare for package
        run: |
          mkdir target
          cp packed/*.c4f target/
          cp packed/*.c4g target/
          cp packed/*.c4d target/
          cp packed/*.c4s target/
          cp clonk_content_license.txt target/
          cp clonk_trademark_license.txt target/
      - uses: actions/upload-artifact@v3
        with:
          name: sc-content
          path: target
      - name: "Release"
        uses: softprops/action-gh-release@v1
        if: ${{ env.IS_RELEASE == 'true' }}
        with:
          files: packed/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
